services:
  sqlite-editor:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - sqlite-tmp:/app/tmp
    environment:
      - NODE_ENV=production

volumes:
  sqlite-tmp:
    driver: local 