name: Deploy to VPS

on:
  push:
    branches:
      - release

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install sshpass for password authentication
      run: |
        sudo apt-get update
        sudo apt-get install -y sshpass

    - name: SSH into VPS and deploy
      run: |
        sshpass -p "${{ secrets.VPS_PASSWORD }}" ssh -o StrictHostKeyChecking=no -p ${{ secrets.VPS_PORT }} ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_HOST }} << 'EOF'
          set -e

          # Install git and docker if not available
          if ! command -v git &> /dev/null; then
            sudo apt update && sudo apt install git -y || sudo yum install git -y || sudo dnf install git -y
          fi
          if ! command -v docker &> /dev/null; then
            sudo apt update && sudo apt install docker.io -y || sudo yum install -y docker || sudo dnf install -y docker
            sudo systemctl start docker
            sudo systemctl enable docker
            sudo usermod -a -G docker ${{ secrets.VPS_USERNAME }}
          fi

          # Trust github.com
          ssh-keyscan github.com >> ~/.ssh/known_hosts || true

          # Pull or clone code
          cd ~
          if [ -d "editsql" ]; then
            cd editsql
            git pull origin release
          else
            git clone https://github.com/toanpn/editsql.git editsql
            cd editsql
          fi

          # Build Docker image
          docker build -t editsql:latest .

          # Stop and remove existing container if running
          if [ $(docker ps -a -q -f name=editsql-container) ]; then
            docker stop editsql-container
            docker rm editsql-container
          fi

          # Run new container
          docker run -d --name editsql-container --restart always -p 3000:3000 editsql:latest

        EOF
