name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup SSH key for EC2
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: SSH into EC2 and deploy
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          set -e

          # Cài git và docker nếu chưa có
          if ! command -v git &> /dev/null; then
            sudo dnf install git -y || sudo yum install git -y
          fi
          if ! command -v docker &> /dev/null; then
            sudo yum install -y docker
            sudo service docker start
            sudo usermod -a -G docker ec2-user
          fi

          # Trust github.com
          ssh-keyscan github.com >> ~/.ssh/known_hosts || true

          # Pull hoặc clone code
          cd ~
          if [ -d "editsql" ]; then
            cd editsql
            git pull origin main
          else
            git clone git@github.com:toanpn/editsql.git editsql
            cd editsql
          fi

          # Build lại Docker image
          docker build -t editsql:latest .

          # Nếu container đang chạy thì stop và remove
          if [ $(docker ps -a -q -f name=editsql-container) ]; then
            docker stop editsql-container
            docker rm editsql-container
          fi

          # Run container mới
          docker run -d --name editsql-container --restart always -p 3000:3000 editsql:latest

        EOF
